networks:
  poker:



services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    networks:
      - poker


  backend:
    build:
      context: ./server
    ports:
      - "3010:3010"
    volumes:
      - ./server:/server
    command: ["node", "app.js"]
    networks:
      - poker

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:88"
    networks:
      - poker
